### ISSUE TITLE
10.0 e-invoicing-vp modules (Módulos para facturación con vp)

### ISSUE THREAD

**Issue by lauracvilla-zz** [odoo-colombia/l10n-colombia#4]
Módulos identificados acorde a la revisión del anexo técnico DIAN:
**NP**: Nombre Propuesto 
**R/**: Responsable 
- [x] **NP** l10n_co_e_invoicing | **R/**  _ @joanmarin y @camilozuluaga _  #10 
- [x] **NP** [l10n_co_account_discrepancy_response](https://github.com/odooloco/l10n-colombia/tree/10.0/l10n_co_account_invoice_discrepancy_response)  | **R/**  _ @camilozuluaga _  #9  
- [x] **NP** l10n_co_account_tax | **R/**  _ @JoanMarin _  #8 Desagregado en:
1. - [x]  [account_invoice_tax_fiscalunit](https://github.com/odooloco/l10n-colombia/tree/10.0/account_invoice_tax_fiscalunit)
2. - [x] [ account_tax_group_menu](https://github.com/odooloco/l10n-colombia/tree/10.0/account_tax_group_menu)
3. - [x]  [account_tax_group_type](https://github.com/odooloco/l10n-colombia/tree/10.0/l10n_co_account_tax_group_type)
4. - [x]  [l10n_co_account_tax_group_type](https://github.com/odooloco/l10n-colombia/tree/10.0/account_tax_group_type)
5. - [x]  [purchase_order_tax_fiscalunit](https://github.com/odooloco/l10n-colombia/tree/10.0/purchase_order_tax_fiscalunit)
6. - [x]  [sale_order_tax_fiscalunit](https://github.com/odooloco/l10n-colombia/tree/10.0/sale_order_tax_fiscalunit)
- [x] **NP** l1[0n_co_account_payment_means](https://github.com/odooloco/l10n-colombia/tree/10.0/l10n_co_account_invoice_payment_mean) | **R/**  _ @camilozuluaga  _  #7  
- [x] **NP** [l10n_co_sequence_resolution](https://github.com/odooloco/l10n-colombia/tree/10.0/l10n_co_sequence_resolution)  | **R/** @JoanMarin #6 
- [x] [l10n_co_base_location](https://github.com/odooloco/l10n-colombia/tree/10.0/l10n_co_base_location) | **R/** @JoanMarin [ver](https://github.com/exaap/l10n-colombia/tree/10.0/l10n_co_base_location)
- [x] **NP** l[10n_co_account_position_list_name](https://github.com/odooloco/l10n-colombia/tree/10.0/l10n_co_account_fiscal_position_list_name) | **R/**  _ @camilozuluaga  _  #5  
- [x] **NP** l[10n_co_partner_tax_level_code](https://github.com/odooloco/l10n-colombia/tree/10.0/l10n_co_partner_tax_level_code)  | **R/** _ @camilozuluaga  _ #3 
- [x] l10n_co_partner_vat |  **R/**  EXA - [ver](https://github.com/exaap/l10n-colombia/blob/10.0/l10n_co_partner_vat)
- [x] partner_other_names | **R/**  EXA - [ver](https://github.com/exaap/l10n-colombia/tree/10.0/partner_other_names)
- [x] partner_second_lastname | **R/**  OCA - [ver](https://github.com/OCA/partner-contact/tree/10.0/partner_second_lastname)
- [x] partner_firstname | **R/** OCA - [ver](https://github.com/OCA/partner-contact/tree/10.0/partner_firstname)
- [x] l10n_co_partner_isic |  **R/**  EXA - [ver](https://github.com/exaap/l10n-colombia/tree/10.0/l10n_co_partner_isic)
- [x] base | **R/** OCA - [ver](https://github.com/OCA/OCB/tree/10.0/odoo/addons/base)
- [x] base_location | **R/** OCA - [ver](https://github.com/OCA/partner-contact/tree/10.0/base_location)
- [x] base_iso3166 | **R/** OCA - [ver](https://github.com/OCA/community-data-files/tree/10.0/base_iso3166)
